### ISSUE TITLE
Sample ToDo List Does not Work for Web

### ISSUE THREAD

**Issue by adrianwi2000** [parse-community/Parse-SDK-JS#1224]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
Downloaded the code per link:
https://blog.back4app.com/expo-react-native/

Works for Android Emulator.

Does not work for the Web.

Error as follows:

TypeError: parse_react_native__WEBPACK_IMPORTED_MODULE_9___default.a.setAsyncStorage is not a function
Module.../../../../../../../../../Users/adrianwilson/Apps/react-native-todoapp-template/App.js
/Users/adrianwilson/Apps/react-native-todoapp-template/App.js:9
   6 | 
   7 | import Parse from "parse/react-native";
   8 | 
>  9 | Parse.setAsyncStorage(AsyncStorage);
  10 | 
  11 | Parse.initialize(keys.applicationId, keys.javascriptKey);
  12 | Parse.serverURL = keys.serverURL;

...

### Steps to reproduce
Once the App has been installed.
Run expo start
Select "Run in Web Browser"

You will get the following error.

### Actual Outcome
Above error

### Expected Outcome
That it will run as in Android emulator.

###  Environment
latest environment per sample.

Server
- Parse Server version: 3.9.0
- Operating system: Mac OS 10.15.6
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): local

Database
- System (MongoDB or Postgres): MongoDB
- Database version: N/A
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): remote

Client
- Parse JS SDK version: 2.4.0

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1094

Please update to the latest version of the SDK and use the following import: (don't forget `.js`)

`import Parse from "parse/react-native.js";`

**Comment by adrianwi2000** [comment]
Hi, thanks for the quick reply. I did change to:

import Parse from "parse/react-native.js";

I now get the following error:
Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage'

**Comment by dplewis** [comment]
This is not an issue with the Parse JS SDK. Questions regarding your implementation and code level questions are better suited on Stack Overflow using the [parse-platform](https://stackoverflow.com/questions/tagged/parse-server) tag. If your question is not appropriate for the site please use our [community forum](https://community.parseplatform.org).

You can also checkout the [README.md](https://github.com/parse-community/Parse-SDK-JS/blob/master/README.md), on how to use AsyncStorage

**Comment by adrianwi2000** [comment]
Thanks for the information.
