### ISSUE TITLE
⚠️ Parse JS SDK 3.5 Issues

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#1615]
## ⚠️ Warning

 The Parse JS SDK [3.5.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0) release contains several bugs due to a [code compilation issue](https://github.com/parse-community/Parse-SDK-JS/pull/1600). We strongly recommend to skip this release.

*Before creating a new issue*, if you encounter any issues, please check which SDK version you are using. To avoid the bug, you can either try the latest alpha version or revert to version 3.4.4. If you still encounter an issue on the latest alpha version, please create a new issue.

TODOs:
- [x] Release fixed beta version https://github.com/parse-community/Parse-SDK-JS/pull/1621
- [x] Release fixed stable version https://github.com/parse-community/Parse-SDK-JS/pull/1622
- [x] Deprecate faulty versions on npm

The following versions were deprecated on npm:
  - 3.5.0-alpha.4
  - 3.5.0-alpha.5
  - 3.5.0-alpha.6
  - 3.5.0-alpha.7
  - 3.5.0-alpha.8
  - 3.5.0-beta.1
  - 3.5.1-alpha.1
  - 3.5.1-beta.1

These versions are not affected (fix already implemented):
  - 3.5.1-alpha.2
  - 3.5.1-beta.2
  - 3.5.1

**Comment by mtrezza** [comment]
- [ ] Release fixed beta version https://github.com/parse-community/Parse-SDK-JS/pull/1621
- [ ] Release fixed stable version
- [ ] Deprecate faulty versions on npm

**Comment by mtrezza** [comment]
@dplewis To your point, I've deprecated the versions on npm and released a new stable version to better inform developers about this issue.
