### ISSUE TITLE
Lock closed threads

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#2013]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Discussions on closed threads are discouraged, among other things due to:
- low visibility, other users are less likely to see the discussion on a closed issue, reducing collaboration
- confusion, since the issue has a "released" tag and comment, but the discussed issue may not have been addressed yet
- future PRs cannot link to a closed issue, which may create multiple "release" tags on a single issue by auto-release, creating even more confusion

To prevent this from happening, issues should be auto-locked after being closed:
https://github.com/marketplace/actions/lock-threads
